### ISSUE TITLE
Выводится не то, что просили

### ISSUE THREAD

**Issue by check-homework** [mrgyf1/GeekBrains#2]
В ТЗ требуется выводить именно 'Fizz' и 'Buzz', это важно!

**Comment by mrgyf1** [comment]
Исправлено, проверь пожалуйста

**Comment by check-homework** [comment]
Да, теперь верно.
Во-первых, ТЗ надо следовать, либо согласовывать изменения, это важно.
Во-вторых, эта задача на смекалку и оптимизацию и фразы для вывода играют большую роль.
Ну что я не просто так докапываюсь )))
